zavrsni_projekt_pzw/main/urls.py
from django.urls import path
from . import views

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('predavaci/', views.PredavacView.as_view(), name='predavaci'),
    path('addpr/', views.PredavacCreateView.as_view(), name='addpr'),
    path('deletepr/<int:pk>', views.PredavacDeleteView.as_view(), name='deletepr'),
    path('updatepr/<int:pk>', views.PredavacUpdateView.as_view(), name='updatepr'),
    
    path('tecajevi/', views.TecajView.as_view(), name='tecajevi'),
    path('addte/', views.TecajCreateView.as_view(), name='addte'),
    path('updatete/<int:pk>', views.TecajUpdateView.as_view(), name='updatete'),
    path('deletete/<int:pk>', views.TecajDeleteView.as_view(), name='deletete'),

    path('prebivaliste/', views.PrebivalisteView.as_view(), name='prebivaliste'),
    path('addpre/', views.PrebivalisteCreateView.as_view(), name='addpre'),
    path('updatepre/<int:pk>', views.PrebivalisteUpdateView.as_view(), name='updatepre'),
    path('deletepre/<int:pk>', views.PrebivalisteDeleteView.as_view(), name='deletepre'),
    
    path('polaznik/', views.PolaznikView.as_view(), name='polaznik'),
    path('addpol/', views.PolaznikCreateView.as_view(), name='addpol'),
    path('updatepol/<int:pk>', views.PolaznikUpdateView.as_view(), name='updatepol'),
    path('deletepol/<int:pk>', views.PolaznikDeleteView.as_view(), name='deletepol'),
    
    path('tjedanradnovrijeme/', views.TjedanradnovrijemeView.as_view(), name='tjedanradnovrijeme'),
    
    path('raspored/', views.RasporedView.as_view(), name='raspored'),
    path('addras/', views.RasporedCreateView.as_view(), name='addras'),
    path('updateras/<int:pk>', views.RasporedUpdateView.as_view(), name='updateras'),
    path('deleteras/<int:pk>', views.RasporedDeleteView.as_view(), name='deleteras'),

    path('ocjena/', views.OcjenaView.as_view(), name='ocjena'),
    path('addocj/', views.OcjenaCreateView.as_view(), name='addocj'),
    path('updateocj/<int:pk>', views.OcjenaUpdateView.as_view(), name='updateocj'),
    path('deleteocj/<int:pk>', views.OcjenaDeleteView.as_view(), name='deleteocj'),
    
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    
    path('pretraga/', views.PredavacListView.as_view(), name='pretraga'),


]

zavrsni_projekt_pzw/zavrsni_projekt_pzw/urls.py
from django.contrib import admin
from django.urls import path, include #importamo include

urlpatterns = [
    path('', include('main.urls')), #dodajemo urls
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))

]

zavrsni_projekt_pzw/main/models.py
from django.db import models
from django.utils import timezone

## Create your models here.


class Predavac(models.Model):
    predavac_ime = models.CharField(max_length=30)
    predavac_prezime = models.CharField(max_length=30)
    predavac_email = models.EmailField()
    predavac_brojSati = models.CharField(max_length=15)

    def __str__(self):
        return '{}'.format(self.predavac_ime + ' ' + self.predavac_prezime)


class Tecaj(models.Model):
    tecaj_naziv = models.CharField(max_length=100)
    tecaj_sadrzaj = models.TextField()
    tecaj_brojSati = models.CharField(max_length=10)
    tecaj_nositelj = models.ForeignKey(Predavac, default=1, on_delete=models.CASCADE)


    def __str__(self):
        return '{}'.format(self.tecaj_naziv + ' (broj sati: ' + self.tecaj_brojSati + ')')
    
class Prebivaliste(models.Model):
    prebivaliste_nazivMjesta = models.CharField(max_length=200)
    prebivaliste_postanskiBroj = models.CharField(max_length=10)
    def __str__(self):
        return '{}'.format(self.prebivaliste_postanskiBroj + ' ' + self.prebivaliste_nazivMjesta)


class Polaznik(models.Model):
    polaznik_ime = models.CharField(max_length=25)
    polaznik_prezime = models.CharField(max_length=50)
    polaznik_oib = models.CharField(max_length=10)
    polaznik_tecaj = models.ManyToManyField(Tecaj)
    polaznik_prebivaliste = models.ForeignKey(Prebivaliste, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.polaznik_ime + ' ' + self.polaznik_prezime)

class TjedanRadnoVrijeme(models.Model):
    dan_u_tjednu = models.CharField(max_length=25)
    termin = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.dan_u_tjednu + ' ' + self.termin)

class Raspored(models.Model):
    termin = models.OneToOneField(
        TjedanRadnoVrijeme,
        on_delete=models.CASCADE,
    )
    tecaj = models.OneToOneField(
        Tecaj,
        on_delete=models.CASCADE,
        primary_key=True
    )

    def __str__(self):
        return '{}'.format(self.tecaj.tecaj_naziv + ' (' + self.termin.dan_u_tjednu + ' ' + self.termin.termin + ')')

class Ocjena(models.Model):
    tecaj = models.ForeignKey(Tecaj, default=1, on_delete=models.CASCADE)
    polaznik = models.ForeignKey(Polaznik, default=1, on_delete=models.CASCADE)
    ocjena = models.CharField(max_length=5)
    polozen_tecaj = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.polaznik.polaznik_ime + ' ' + self.polaznik.polaznik_prezime + ' (Ocjena ' + self.ocjena + ')')

zavrsni_projekt_pzw/main/forms.py
from django import forms
from .models import *

class PredavacForm(forms.ModelForm):
    class Meta:
        model = Predavac
        fields = ['predavac_ime', 'predavac_prezime', 'predavac_email', 'predavac_brojSati']

class TecajForm(forms.ModelForm):
    class Meta:
        model = Tecaj
        fields = ['tecaj_naziv', 'tecaj_sadrzaj', 'tecaj_brojSati', 'tecaj_nositelj']
        
class PrebivalisteForm(forms.ModelForm):
    class Meta:
        model = Prebivaliste
        fields = ['prebivaliste_nazivMjesta', 'prebivaliste_postanskiBroj']

class PolaznikForm(forms.ModelForm):
    class Meta:
        model = Polaznik
        fields = ['polaznik_ime', 'polaznik_prezime', 'polaznik_oib', 'polaznik_tecaj', 'polaznik_prebivaliste']
        
class RasporedForm(forms.ModelForm):
    class Meta:
        model = Raspored
        fields = ['termin', 'tecaj']
        
class OcjenaForm(forms.ModelForm):
    class Meta:
        model = Ocjena
        fields = ['tecaj', 'polaznik', 'ocjena', 'polozen_tecaj']

zavrsni_projekt_pzw/main/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import *
from django.views.generic import *
from main.models import *

from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from .models import *
from .forms import *

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


class HomePageView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'home.html')

def landing_page(request):
    return render(request, 'home.html')

class PredavacView(ListView):
    model = Predavac
    
class PredavacListView(ListView):
    model = Predavac
    template_name = 'main/list_predavac.html'
    context_object_name = 'predavac'
    
class PredavacDeleteView(DeleteView):
    model = Predavac
    template_name = 'deletepr_predavac.html'
    success_url = reverse_lazy('main:predavaci')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['predavac'] = self.get_object()
        return context

class PredavacCreateView(CreateView):
    model = Predavac
    form_class = PredavacForm
    template_name = 'add_predavac.html'
    success_url = reverse_lazy('main:predavaci')    
    
class PredavacUpdateView(UpdateView):
    model = Predavac
    form_class = PredavacForm
    template_name = 'update_predavac.html'
    success_url = reverse_lazy('main:predavaci')    
    
class TecajView(ListView):
    model = Tecaj

class TecajCreateView(CreateView):
    model = Tecaj
    form_class = TecajForm
    template_name = 'add_tecaj.html'
    success_url = reverse_lazy('main:tecajevi')    
    
class TecajUpdateView(UpdateView):
    model = Tecaj
    form_class = TecajForm
    template_name = 'update_tecaj.html'
    success_url = reverse_lazy('main:tecajevi')    
    
class TecajDeleteView(DeleteView):
    model = Tecaj
    template_name = 'delete_tecaj.html'
    success_url = reverse_lazy('main:tecajevi')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tecaj'] = self.get_object()
        return context
    
class PrebivalisteView(ListView):
    model = Prebivaliste

class PrebivalisteCreateView(CreateView):
    model = Prebivaliste
    form_class = PrebivalisteForm
    template_name = 'add_prebivaliste.html'
    success_url = reverse_lazy('main:prebivaliste')    
    
class PrebivalisteUpdateView(UpdateView):
    model = Prebivaliste
    form_class = PrebivalisteForm
    template_name = 'update_prebivaliste.html'
    success_url = reverse_lazy('main:prebivaliste')    
    
class PrebivalisteDeleteView(DeleteView):
    model = Prebivaliste
    template_name = 'delete_prebivaliste.html'
    success_url = reverse_lazy('main:prebivaliste')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prebivaliste'] = self.get_object()
        return context
    
class PolaznikView(ListView):
    model = Polaznik

class PolaznikCreateView(CreateView):
    model = Polaznik
    form_class = PolaznikForm
    template_name = 'add_polaznik.html'
    success_url = reverse_lazy('main:polaznik')    
    
class PolaznikUpdateView(UpdateView):
    model = Polaznik
    form_class = PolaznikForm
    template_name = 'update_polaznik.html'
    success_url = reverse_lazy('main:polaznik')    
    
class PolaznikDeleteView(DeleteView):
    model = Polaznik
    template_name = 'delete_polaznik.html'
    success_url = reverse_lazy('main:polaznik')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['polaznik'] = self.get_object()
        return context
    
class TjedanradnovrijemeView(ListView):
    model = TjedanRadnoVrijeme
    
class RasporedView(ListView):
    model = Raspored

class RasporedCreateView(CreateView):
    model = Raspored
    form_class = RasporedForm
    template_name = 'add_raspored.html'
    success_url = reverse_lazy('main:raspored')    
    
class RasporedUpdateView(UpdateView):
    model = Raspored
    form_class = RasporedForm
    template_name = 'update_raspored.html'
    success_url = reverse_lazy('main:raspored')    
    
class RasporedDeleteView(DeleteView):
    model = Raspored
    template_name = 'delete_raspored.html'
    success_url = reverse_lazy('main:raspored')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['raspored'] = self.get_object()
        return context
    
class OcjenaView(ListView):
    model = Ocjena

class OcjenaCreateView(CreateView):
    model = Ocjena
    form_class = OcjenaForm
    template_name = 'add_ocjena.html'
    success_url = reverse_lazy('main:ocjena')    
    
class OcjenaUpdateView(UpdateView):
    model = Ocjena
    form_class = OcjenaForm
    template_name = 'update_ocjena.html'
    success_url = reverse_lazy('main:ocjena')    
    
class OcjenaDeleteView(DeleteView):
    model = Ocjena
    template_name = 'delete_ocjena.html'
    success_url = reverse_lazy('main:ocjena')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ocjena'] = self.get_object()
        return context
    

## Create your views here.
def index(request):
    return render(request, './home.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main:index')

    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)

zavrsni_projekt_pzw/main/templates/main/list_predavac.html
{% extends "home.html" %}
{% block content %}
<br>
<h2> Pretraga </h2>
<br>
<ul>
    {% for predavac in predavac %}
        {% if predavac.predavac_ime|first == 'm' or predavac.predavac_ime|first == 'M' %}
            <li>{{ predavac.predavac_ime }} {{ predavac.predavac_prezime }}</li>
        {% endif %}
    {% empty %}
        <li>Nema predavača čije ime započinje s 'M'</li>
    {% endfor %}
</ul>
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/ocjena_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Ocjene</h2>
<br>
<a style="color: green;" href="{% url 'main:addocj' %}">Dodaj ocjenu</a>
{% for ocjena in ocjena_list %}
    <div class="book">
        <h4>Polaznik: {{ ocjena.polaznik}}</h4>
        <p>Tecaj: {{ ocjena.tecaj }} <br>
        Ocjena: {{ ocjena.ocjena}}<br>
        Polozen tecaj: {{ ocjena.polozen_tecaj}}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updateocj' ocjena.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deleteocj' ocjena.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/polaznik_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Polaznik</h2>
<br>
<a style="color: green;" href="{% url 'main:addpol' %}">Dodaj polaznika</a>
{% for polaznik in polaznik_list %}
    <div class="book">
        <h4>Ime i prezime: {{ polaznik.polaznik_ime }} {{polaznik.polaznik_prezime }}</h4>
        <p>OIB: {{ polaznik.polaznik_oib}}<br>
        Prebivaliste: {{ polaznik.polaznik_prebivaliste}}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updatepol' polaznik.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deletepol' polaznik.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/prebivaliste_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Prebivaliste</h2>
<br>
<a style="color: green;" href="{% url 'main:addpre' %}">Dodaj prebivaliste</a>
{% for prebivaliste in prebivaliste_list %}
    <div class="book">
        <h4>Naziv mjesta: {{ prebivaliste.prebivaliste_nazivMjesta }} </h4>
        <p>Postanski broj: {{ prebivaliste.prebivaliste_postanskiBroj }}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updatepre' prebivaliste.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deletepre' prebivaliste.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/predavac_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Predavac</h2>
<br>
<a style="color: green;" href="{% url 'main:addpr' %}">Dodaj predavaca</a>
{% for predavac in predavac_list %}
    <div class="book">
        <h4>Ime i prezime: {{ predavac.predavac_ime }} {{ predavac.predavac_prezime }}</h4>
        <p>Email: {{ predavac.predavac_email }}<br>
        Broj sati: {{ predavac.predavac_brojSati }}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updatepr' predavac.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deletepr' predavac.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/predavacc_list.html
!DOCTYPE html>
<html>
<head>
    <title>List Ice Creams</title>
</head>
<body>
    <h1>List of Predavacs</h1>
    <ul>
        {% for predavac in predavac %}

            <li>{{ predavac.predavac_ime }} - Price: ${{ predavac.predavac_prezime }}</li>
          
        {% empty %}
            <li>No ice creams available</li>
        {% endfor %}
    </ul>
</body>
</html>
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/raspored_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Raspored</h2>
<br>
<a style="color: green;" href="{% url 'main:addras' %}">Dodaj raspored</a>
{% for raspored in raspored_list %}
    <div class="book">
        <h4>Termin: {{ raspored.termin }}</h4>
        <p>Tecaj: {{ raspored.tecaj }}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updateras' raspored.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deleteras' raspored.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/tecaj_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Tecaj</h2>
<br>
<a style="color: green;" href="{% url 'main:addte' %}">Dodaj tecaj</a>
{% for tecaj in tecaj_list %}
    <div class="book">
        <h4>Naziv: {{ tecaj.tecaj_naziv }} </h4>
        <p>Sadrzaj: {{ tecaj.tecaj_sadrzaj }}<br>
        Broj sati: {{ tecaj.tecaj_brojSati }}<br>
        Nositelj: {{ tecaj.tecaj_nositelj }}</p>
    </div>
    <a style="color: #003749;" href="{% url 'main:updatete' tecaj.pk %}">Azuriraj</a>
    <a style="color: red;" href="{% url 'main:deletete' tecaj.pk %}">Obrisi</a>
{% endfor %}
{% endblock %}

zavrsni_projekt_pzw/main/templates/main/tjedanradnovrijeme_list.html
{% extends "home.html" %}
{% block content %}
<br>
<h2 style="color: gray;">Opcije radnog vremen preko tjedna</h2>
<br>
{% for tjedanradnovrijeme in tjedanradnovrijeme_list %}
    <div class="book">
        <h4>Naziv: {{ tjedanradnovrijeme.dan_u_tjednu }} {{ tjedanradnovrijeme.termin }}  </h4>
    </div>
{% endfor %}
{% endblock %}